AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Inventario HVAC Backend - Lambda + API Gateway + VPC
Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: nodejs20.x

Parameters:
  DatabaseUrl:
    Type: String
    NoEcho: true
    Description: URL de conexion a la base de datos
  JwtSecret:
    Type: String
    NoEcho: true
    Description: Secreto usado para firmar los tokens JWT

Resources:
  InventarioApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: inventario-hvac-api
      CodeUri: .
      Handler: src/lambda.handler

      Environment:
        Variables:
          NODE_ENV: production
          DATABASE_URL: !Ref DatabaseUrl
          JWT_SECRET: !Ref JwtSecret
          FRONTEND_URL: "http://localhost:5173,http://localhost:5174"
          S3_BUCKET_NAME: "inventario-venegas-files"

      VpcConfig:
        SecurityGroupIds:
          - sg-0ab4f70c826c86900
        SubnetIds:
          - subnet-06b5859ab32be7d18
          - subnet-0ad4ca13e514ad92e

      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaVPCAccessExecutionRole
        - S3CrudPolicy:
            BucketName: inventario-venegas-files

      Events:
        ApiRoot:
          Type: HttpApi
          Properties:
            Path: /
            Method: ANY

        ApiProxy:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  ApiUrl:
    Description: URL publica de la API
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
